# Generated by Django 4.1.6 on 2023-02-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publikasi', '0002_testimoni'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='pengumuman',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='testimoni',
            name='image',
            field=models.FileField(upload_to='publikasi/testimoni/'),
        ),
    ]
