# Generated by Django 4.1.6 on 2023-02-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.FileField(null=True, upload_to='event/logo/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='nominal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='total_nominal',
            field=models.IntegerField(),
        ),
    ]
