# Generated by Django 4.1.6 on 2023-02-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_logo_alter_event_nominal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuriEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('image', models.FileField(upload_to='juri/foto/')),
                ('video', models.FileField(upload_to='juri/video/')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('logo', models.FileField(upload_to='event/sponsor/')),
            ],
        ),
    ]
