# Generated by Django 4.1.6 on 2023-02-05 18:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no_hp',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uniid',
            field=models.UUIDField(default=uuid.UUID('de9773cd-bbea-4787-9da1-9e574583cba1'), editable=False),
        ),
    ]
