# Generated by Django 4.1.6 on 2023-02-05 18:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_no_hp_alter_user_uniid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jenjang',
            field=models.CharField(default='smp', max_length=3, verbose_name=[('smp', 'SMP'), ('sma', 'SMA'), ('sd', 'SD'), ('tk', 'TK')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='uniid',
            field=models.UUIDField(default=uuid.UUID('36b38130-4a13-4b7f-8080-3569bf9ae62f'), editable=False),
        ),
    ]
