# Generated by Django 4.1.6 on 2023-02-05 18:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_jenjang_alter_user_uniid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uniid',
            field=models.UUIDField(default=uuid.UUID('182d62ac-af12-4a31-a9a4-895d286b7b3c'), editable=False),
        ),
    ]
