# Generated by Django 4.1.6 on 2023-02-05 19:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_active_alter_user_uniid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jenjang',
            field=models.CharField(choices=[('smp', 'SMP'), ('sma', 'SMA'), ('sd', 'SD'), ('tk', 'TK')], default='smp', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='uniid',
            field=models.UUIDField(default=uuid.UUID('3971e29f-204d-43c8-abb5-0eb2339316d0'), editable=False),
        ),
    ]
